CREATE TABLE STUDENT(
    STU_NO NUMBER NOT NULL,
    STU_NAME VARCHAR2(5 BYTE) NOT NULL,
    STU_ADRESS VARCHAR2 NULL,
    STU_GRADE VARCHAR2 NOT NULL,
    STU_PRO_PN VARCHAR NULL
);

CREATE TABLE PROFESSOR(
    PRO_NO NUMBER NOT NULL,
    PRO_NAME VARCHAR NOT NULL,
    PRO_SPE VARCHAR NOT NULL
);   

CREATE TABLE LECTURE(
    LEC_NO NUMBER NOT NULL,
    PRO_NO NUMBER NOT NULL,
    ENR_NO NUMBER NOT NULL,
    LEC_NAME VARCHAR2 NOT NULL,
    LEC_PLC VARCHAR2 NOT NULL
);

CREATE TABLE ENROLL(
    ENR_NO NUMBER NOT NULL,
    STU_NO NUMBER NOT NULL,
    COU_NO NUMBER NOT NULL,
    ENR DATE NOT NULL
);

CREATE TABLE COURSE(
    COU_NO NUMBER NOT NULL,
    COU_NAME VARCHAR2 NOT NULL,
    COU_GRA NUMBER NULL
);

-- 기본키 추가 
ALTER TABLE STUDENT 
    ADD CONSTRAINT PK_STU PRIMARY KEY(STU_NO);
    
ALTER TABLE PROFESSOR
    ADD CONSTRAINT PK_PRO PRIMARY KEY(PRO_NO);
    
ALTER TABLE LECTURE
    ADD CONSTRAINT PK_LEC PRIMARY KEY(LEC_NO);
    
ALTER TABLE ENROLL
    ADD CONSTRAINT PK_ENROLL PRIMARY KEY (ENR_NO);

ALTER TABLE COURSE
    ADD CONSTRAINT PK_COURSE PRIMARY KEY(COU_NO);
    
-- 외래키 추가

    
    