DROP TABLE STAFT;
create table staft (
SNO VARCHAR2(5 BYTE) NOT NULL,
NAME VARCHAR2(32 BYTE),
DEPT VARCHAR2(20 BYTE) NOT NULL,
SALARY NUMBER NOT NULL,
CONSTRAINT PK_STAFT PRIMARY KEY(SNO)
);

INSERT INTO STAFT VALUES('11111', '설경구', '기획부', 5000);
INSERT INTO STAFT VALUES('22222', '전지현', '개발부', 6000);
INSERT INTO STAFT VALUES('33333', '정우성', '영업부', 7000);
COMMIT;