DROP TABLE POST;
CREATE TABLE POST (
    NO NUMBER PRIMARY KEY, 
    WRITER VARCHAR2(100 BYTE),
    CONTENT VARCHAR2(4000 BYTE),
    IP VARCHAR2(50 BYTE),
    HIT NUMBER,
    CREATE_DATE DATE,
    MODIFY_DATE DATE
    );
    
DROP SEQUENCE POST_SEQ;
CREATE SEQUENCE POST_SEQ;